<a href="https://colab.research.google.com/github/ranjanvrma/retail-sales-analytics/blob/main/notebooks/02_exploratory_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import pandas as pd
import seaborn as sns

In [103]:
df = pd.read_csv('/content/superstore_sales.csv')

In [104]:
df.shape

(9800, 18)

In [105]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [106]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

In [107]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [108]:
df.dropna(inplace=True)

In [109]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

## Sales Performance

In [110]:
# Which region generates the highest sales?
df.groupby('Region')['Sales'].sum().sort_values(ascending = False)

Region
West       710219.6845
East       660589.3560
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [111]:
# Which state generates the highest sales?
df.groupby('State')['Sales'].sum().sort_values(ascending = False).head()

State
California      446306.4635
New York        306361.1470
Texas           168572.5322
Washington      135206.8500
Pennsylvania    116276.6500
Name: Sales, dtype: float64

In [112]:
# Which category generates the highest sales?
df.groupby('Category')['Sales'].sum().sort_values(ascending = False)

Category
Technology         825856.1130
Furniture          723538.4757
Office Supplies    703212.8240
Name: Sales, dtype: float64

In [113]:
# Which sub-category generates the highest sales?
df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending = False).head()

Sub-Category
Phones     326487.698
Chairs     322107.531
Storage    217779.102
Tables     202810.628
Binders    200028.785
Name: Sales, dtype: float64

In [114]:
# Which products generate the highest sales?
df.groupby(['Product ID', 'Product Name'])['Sales'].sum().sort_values(ascending = False).head()

Product ID       Product Name
TEC-CO-10004722  Canon imageCLASS 2200 Advanced Copier                                          61599.824
OFF-BI-10003527  Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
TEC-MA-10002412  Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
FUR-CH-10002024  HON 5400 Series Task Chairs for Big and Tall                                   21870.576
OFF-BI-10001359  GBC DocuBind TL300 Electric Binding System                                     19823.479
Name: Sales, dtype: float64

## Customer Analysis

In [115]:
# Which customer has spent the most?
df.groupby(['Customer ID', 'Customer Name'])['Sales'].sum().sort_values(ascending = False).head()

Customer ID  Customer Name
SM-20320     Sean Miller      25043.050
TC-20980     Tamara Chand     19052.218
RB-19360     Raymond Buch     15117.339
TA-21385     Tom Ashbrook     14595.620
AB-10105     Adrian Barton    14473.571
Name: Sales, dtype: float64

In [116]:
# Which customer segment contributes the most revenue?
df.groupby('Segment')['Sales'].sum().sort_values(ascending = False)

Segment
Consumer       1.146708e+06
Corporate      6.822118e+05
Home Office    4.236874e+05
Name: Sales, dtype: float64

In [117]:
# Top 10 customers by sales.
df.groupby(['Customer ID', 'Customer Name'])['Sales'].sum().sort_values(ascending = False).head(10)

Customer ID  Customer Name
SM-20320     Sean Miller           25043.050
TC-20980     Tamara Chand          19052.218
RB-19360     Raymond Buch          15117.339
TA-21385     Tom Ashbrook          14595.620
AB-10105     Adrian Barton         14473.571
KL-16645     Ken Lonsdale          14175.229
SC-20095     Sanjit Chand          14142.334
HL-15040     Hunter Lopez          12873.298
SE-20110     Sanjit Engle          12209.438
CC-12370     Christopher Conant    12129.072
Name: Sales, dtype: float64

## Shipping

In [118]:
# Which shipping mode is used the most?
df.groupby('Ship Mode')['Order ID'].count().sort_values(ascending = False)

Ship Mode
Standard Class    5849
Second Class      1901
First Class       1501
Same Day           538
Name: Order ID, dtype: int64

In [119]:
# Which shipping mode generates the highest sales?
df.groupby('Ship Mode')['Sales'].sum().sort_values(ascending = False)

Ship Mode
Standard Class    1.332617e+06
Second Class      4.491990e+05
First Class       3.455723e+05
Same Day          1.252190e+05
Name: Sales, dtype: float64

## Geography

In [120]:
# Top 10 cities by sales.
df.groupby('City')['Sales'].sum().sort_values(ascending = False).head(10)

City
New York City    252462.5470
Los Angeles      173420.1810
Seattle          116106.3220
San Francisco    109041.1200
Philadelphia     108841.7490
Houston           63956.1428
Chicago           47820.1330
San Diego         47521.0290
Jacksonville      44713.1830
Detroit           42446.9440
Name: Sales, dtype: float64

In [121]:
# Sales distribution by region.
df.groupby('Region')['Sales'].sum().sort_values(ascending = False)

Region
West       710219.6845
East       660589.3560
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

## Time Analysis

In [122]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format = '%d/%m/%Y')

In [123]:
# Sales by Year
df.groupby(df['Order Date'].dt.year)['Sales'].sum()

Order Date
2015    479856.2081
2016    454315.9054
2017    597225.4900
2018    721209.8092
Name: Sales, dtype: float64

In [124]:
# Sales by Month
monthly_sales = df.groupby(df['Order Date'].dt.month)['Sales'].sum()

monthly_sales.index = pd.to_datetime(monthly_sales.index, format = '%m').month_name()
monthly_sales

Order Date
January       91982.1396
February      59371.1154
March        197573.5872
April        134988.2506
May          154086.7237
June         145837.5233
July         145535.6890
August       157315.9270
September    300103.4117
October      199496.2947
November     345041.6110
December     321275.1395
Name: Sales, dtype: float64

In [125]:
# Which month has the highest sales?
df.groupby(df['Order Date'].dt.month_name())['Sales'].sum().sort_values(ascending = False).head()

Order Date
November     345041.6110
December     321275.1395
September    300103.4117
October      199496.2947
March        197573.5872
Name: Sales, dtype: float64

In [126]:
# Which year had the highest sales?
df.groupby(df['Order Date'].dt.year)['Sales'].sum().sort_values(ascending = False)

Order Date
2018    721209.8092
2017    597225.4900
2015    479856.2081
2016    454315.9054
Name: Sales, dtype: float64