<a href="https://colab.research.google.com/github/ranjanvrma/retail-sales-analytics/blob/main/notebooks/03_business_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import seaborn as sns

In [60]:
df = pd.read_csv('/content/superstore_sales.csv')

In [61]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [62]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [63]:
df.dropna(inplace = True)

In [64]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

## Sales Analysis

In [65]:
# What is the total revenue?
Total_Sales = df['Sales'].sum()
print(Total_Sales)

2252607.4127

In [66]:
# What is the average sale amount?
Average_Sales = df['Sales'].mean()
print(Average_Sales)

230.1161929410563

In [67]:
# Which category generates the highest sales?
df.groupby('Category')['Sales'].sum().sort_values(ascending = True)

Category
Office Supplies    703212.8240
Furniture          723538.4757
Technology         825856.1130
Name: Sales, dtype: float64

In [68]:
# Which sub-category generates the highest sales?
df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending = False).head()

Sub-Category
Phones     326487.698
Chairs     322107.531
Storage    217779.102
Tables     202810.628
Binders    200028.785
Name: Sales, dtype: float64

In [69]:
# Top 10 products by sales.
df.groupby('Product Name')['Sales'].sum().sort_values(ascending = False).head(10)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [70]:
# Bottom 10 products by sales.
df.groupby('Product Name')['Sales'].sum().sort_values(ascending = False).tail(10)

Product Name
Acco Economy Flexible Poly Round Ring Binder                        8.352
Stockwell Gold Paper Clips                                          8.096
Xerox 1989                                                          7.968
Avery Hi-Liter Comfort Grip Fluorescent Highlighter, Yellow Ink     7.800
Avery Hi-Liter Pen Style Six-Color Fluorescent Set                  7.700
Acme Serrated Blade Letter Opener                                   7.632
Grip Seal Envelopes                                                 7.072
Xerox 20                                                            6.480
Avery 5                                                             5.760
Eureka Disposable Bags for Sanitaire Vibra Groomer I Upright Vac    1.624
Name: Sales, dtype: float64

In [71]:
# What percentage of total sales comes from each category?
df.groupby('Category')['Sales'].sum() / df['Sales'].sum() * 100

Category
Furniture          32.120043
Office Supplies    31.217727
Technology         36.662230
Name: Sales, dtype: float64

In [72]:
# What percentage of total sales comes from each region?
df.groupby('Region')['Sales'].sum() / df['Sales'].sum() * 100

Region
Central    21.870074
East       29.325543
South      17.275601
West       31.528782
Name: Sales, dtype: float64

## Customer Analysis

In [73]:
# How many unique customers are there?
df['Customer ID'].nunique()

793

In [74]:
# Top 10 customers by sales.
df.groupby(['Customer ID', 'Customer Name'])['Sales'].sum().sort_values(ascending = False).head(10)

Customer ID  Customer Name
SM-20320     Sean Miller           25043.050
TC-20980     Tamara Chand          19052.218
RB-19360     Raymond Buch          15117.339
TA-21385     Tom Ashbrook          14595.620
AB-10105     Adrian Barton         14473.571
KL-16645     Ken Lonsdale          14175.229
SC-20095     Sanjit Chand          14142.334
HL-15040     Hunter Lopez          12873.298
SE-20110     Sanjit Engle          12209.438
CC-12370     Christopher Conant    12129.072
Name: Sales, dtype: float64

In [75]:
# Average spending per customer.
df.groupby(['Customer ID', 'Customer Name'])['Sales'].mean()

Customer ID  Customer Name
AA-10315     Alex Avila            505.778182
AA-10375     Allen Armold           70.426000
AA-10480     Andrew Allen          149.209333
AA-10645     Anna Andreadi         282.607500
AB-10015     Aaron Bergman         147.692667
                                      ...
XP-21865     Xylona Preis           84.809214
YC-21895     Yoseph Carroll        681.793750
YS-21880     Yana Sorensen         560.037000
ZC-21910     Zuschuss Carroll      258.893774
ZD-21925     Zuschuss Donatelli    165.993778
Name: Sales, Length: 793, dtype: float64

In [76]:
# Which customer segment contributes the most revenue?
df.groupby('Segment')['Sales'].sum().sort_values(ascending = False)

Segment
Consumer       1.146708e+06
Corporate      6.822118e+05
Home Office    4.236874e+05
Name: Sales, dtype: float64

In [77]:
# Which customers placed the most orders?
df[['Customer ID', 'Customer Name']].value_counts().head()

Customer ID  Customer Name
WB-21850     William Brown    35
MA-17560     Matt Abelman     34
PP-18955     Paul Prost       34
JL-15835     John Lee         33
SV-20365     Seth Vernon      32
Name: count, dtype: int64

In [78]:
# Find repeat customers (customers with more than one order).
df['Customer ID'].value_counts()[lambda x: x > 1]

Customer ID
WB-21850    35
PP-18955    34
MA-17560    34
JL-15835    33
CK-12205    32
            ..
MG-18205     2
RM-19750     2
EL-13735     2
PH-18790     2
AR-10570     2
Name: count, Length: 787, dtype: int64

## Product Analysis

In [79]:
# Average sales for each category.
df.groupby('Category')['Sales'].mean()

Category
Furniture          348.525277
Office Supplies    119.128041
Technology         456.274096
Name: Sales, dtype: float64

In [80]:
# Average sales for each sub-category.
df.groupby('Sub-Category')['Sales'].mean()

Sub-Category
Accessories     217.349721
Appliances      227.239002
Art              34.052768
Binders         134.067550
Bookcases       486.259105
Chairs          531.530579
Copiers        2215.880212
Envelopes        65.287474
Fasteners        14.027850
Furnishings      95.823865
Labels           34.587468
Machines       1645.553313
Paper            57.437204
Phones          373.128798
Storage         262.068715
Supplies        252.284283
Tables          645.893720
Name: Sales, dtype: float64

In [81]:
# Best-selling product in each category.
product_sales = df.groupby(['Category', 'Product Name'])['Sales'].sum().sort_values(ascending = False)
product_sales.loc[product_sales.groupby(level = 0).idxmax()]

Category         Product Name
Furniture        HON 5400 Series Task Chairs for Big and Tall                                   21870.576
Office Supplies  Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Technology       Canon imageCLASS 2200 Advanced Copier                                          61599.824
Name: Sales, dtype: float64

In [82]:
# Top 5 products in Technology.
tech = df[df['Category'] == 'Technology']
tech.groupby( 'Sub-Category')['Sales'].sum().sort_values(ascending = False)

Sub-Category
Phones         326487.698
Machines       189238.631
Accessories    163881.690
Copiers        146248.094
Name: Sales, dtype: float64

## Geographic Analysis

In [83]:
# Top 10 cities by sales.
df.groupby('City')['Sales'].sum().sort_values(ascending = False).head(10)

City
New York City    252462.5470
Los Angeles      173420.1810
Seattle          116106.3220
San Francisco    109041.1200
Philadelphia     108841.7490
Houston           63956.1428
Chicago           47820.1330
San Diego         47521.0290
Jacksonville      44713.1830
Detroit           42446.9440
Name: Sales, dtype: float64

In [84]:
# Top 10 states by sales.
df.groupby('State')['Sales'].sum().sort_values(ascending = False).head(10)

State
California      446306.4635
New York        306361.1470
Texas           168572.5322
Washington      135206.8500
Pennsylvania    116276.6500
Florida          88436.5320
Illinois         79236.5170
Michigan         76136.0740
Ohio             75130.3500
Virginia         70636.7200
Name: Sales, dtype: float64

In [85]:
# Which region generates the highest revenue?
df.groupby('Region')['Sales'].sum().sort_values(ascending = False)

Region
West       710219.6845
East       660589.3560
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

In [86]:
# Best-selling category in every region.
best_selling = df.groupby(['Region', 'Category'])['Sales'].sum()
best_selling.loc[best_selling.groupby(level = 0).idxmax()]

Region   Category
Central  Technology    168739.208
East     Technology    261516.767
South    Technology    148195.208
West     Technology    247404.930
Name: Sales, dtype: float64

In [87]:
# Average sales in each state.
df.groupby('State')['Sales'].mean().head()

State
Alabama       319.846557
Arizona       158.173350
Arkansas      194.635500
California    229.345562
Colorado      177.886022
Name: Sales, dtype: float64

## Time Analysis

In [88]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format = '%d/%m/%Y')

In [89]:
# Year-wise sales.
df.groupby(df['Order Date'].rename('Year').dt.year)['Sales'].sum()

Year
2015    479856.2081
2016    454315.9054
2017    597225.4900
2018    721209.8092
Name: Sales, dtype: float64

In [90]:
# Month-wise sales.
monthly_sales = df.groupby(df['Order Date'].rename('Month').dt.month)['Sales'].sum()
monthly_sales.index = pd.to_datetime(monthly_sales.index, format = '%m').month_name()
monthly_sales

Month
January       91982.1396
February      59371.1154
March        197573.5872
April        134988.2506
May          154086.7237
June         145837.5233
July         145535.6890
August       157315.9270
September    300103.4117
October      199496.2947
November     345041.6110
December     321275.1395
Name: Sales, dtype: float64

In [91]:
# Quarter-wise sales.
df.groupby(df['Order Date'].rename('Quarter').dt.quarter)['Sales'].sum()

Quarter
1    348926.8422
2    434912.4976
3    602955.0277
4    865813.0452
Name: Sales, dtype: float64

In [92]:
# Highest sales month.
monthly_sales = df.groupby(df['Order Date'].rename('Month').dt.month)['Sales'].sum().sort_values(ascending = False)
monthly_sales.index = pd.to_datetime(monthly_sales.index, format = '%m').month_name()
monthly_sales.head(1)

Month
November    345041.611
Name: Sales, dtype: float64

In [93]:
# Highest sales year.
df.groupby(df['Order Date'].dt.year)['Sales'].sum().sort_values(ascending = False)

Order Date
2018    721209.8092
2017    597225.4900
2015    479856.2081
2016    454315.9054
Name: Sales, dtype: float64